-- AlterTable
ALTER TABLE "Mtr" ALTER COLUMN "shipmentItemId" SET DATA TYPE TEXT,
ALTER COLUMN "invoiceAmount" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "total" SET DATA TYPE TEXT;
